apiVersion: v1
data:
  filebeat.yml: |-
    filebeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
    filebeat.inputs:
    - type: container
      enabled: true
      paths:
      - /var/log/containers/paas-*log
      - /var/log/containers/ack-ingress-nginx-gateway-controller-*.log
      multiline.pattern: ^\d{4}\-\d{2}\-\d{2}
      multiline.negate: true
      multiline.match: after
      multiline.timeout: 10s
      multiline.max_lines: 300
      max_procs: 1
      fields_under_root: true
    processors:
    - add_kubernetes_metadata:
        in_cluster: true
        default_indexers.enabled: true
        default_matchers.enabled: true
        host: ${NODE_NAME}
        pod_name: ${POD_NAME}
        pod_namespace: ${POD_NAMESPACE}
        pod_ip: ${POD_IP}
        matchers:
        - logs_path:
           logs_path: "/var/log/containers/"
    - drop_event.when.regexp:
        or:
           kubernetes.pod.name: "filebeat.*"
           kubernetes.pod.name: "external-dns.*"
           kubernetes.pod.name: "coredns.*"
    - drop_fields:
        fields:
           - host
           - tags
           - ecs
           #- log
           - prospector
           - agent
           - input
           - beat
           - offset
           - stream
           - container
           - kubernetes
        ignore_missing: true


    output.kafka:
      hosts: ["10.255.0.96:9092","10.255.0.95:9092","10.255.0.90:9092"]
      version: "0.10.2.1"
      topic: "paas-logger"
      required_acks: 1
      compression: none
      max_message_bytes: 1000000
      partition.round_robin:
        reachable_only: true
kind: ConfigMap
metadata:
  annotations: {}
  name: filebeat-config
  namespace: kube-system


---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations: {}
  labels:
    k8s-app: filebeat
  name: filebeat
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      containers:
        - args:
            - -c
            - /etc/filebeat.yml
            - -e
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: docker.elastic.co/beats/filebeat:7.15.2-amd64
          imagePullPolicy: IfNotPresent
          name: filebeat
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/filebeat.yml
              name: config
              readOnly: true
              subPath: filebeat.yml
            - mountPath: /usr/share/filebeat/data
              name: data
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /var/log
              name: varlog
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: filebeat
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 416
            name: filebeat-config
          name: config
        - hostPath:
            path: /var/lib/docker/containers
            type: ""
          name: varlibdockercontainers
        - hostPath:
            path: /var/log
            type: ""
          name: varlog
        - hostPath:
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate
          name: data
  templateGeneration: 2
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

