kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-db-config
  namespace: haagendazstest
  labels:
    app: mysql-db
data:
  my.cnf: |
    [client]
    default-character-set=utf8mb4
    [mysql]
    default-character-set=utf8mb4
    [mysqld]
    max_connections = 2000
    secure_file_priv=/var/lib/mysql
    #sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

    default_time_zone = "+8:00"
    skip_name_resolve = 1
    open_files_limit    = 65535
    back_log = 1024
    max_connect_errors = 1000000
    table_open_cache = 1024
    table_definition_cache = 1024
    table_open_cache_instances = 64
    thread_stack = 512K
    external-locking = FALSE
    max_allowed_packet = 32M
    sort_buffer_size = 16M
    join_buffer_size = 16M
    thread_cache_size = 768
    interactive_timeout = 600
    wait_timeout = 600
    tmp_table_size = 96M
    max_heap_table_size = 96M
    slow_query_log = 1
    log_timestamps = SYSTEM
    long_query_time = 0.1
    log_queries_not_using_indexes =1
    log_throttle_queries_not_using_indexes = 60
    min_examined_row_limit = 100
    log_slow_admin_statements = 1
    log_slow_slave_statements = 1
    server-id = 3306
    sync_binlog = 1
    binlog_cache_size = 4M
    max_binlog_cache_size = 2G
    max_binlog_size = 1G
    
    expire_logs_days = 7
    
    master_info_repository = TABLE
    relay_log_info_repository = TABLE
    gtid_mode = on
    enforce_gtid_consistency = 1
    log_slave_updates
    binlog_format = row
    binlog_checksum = 1
    relay_log_recovery = 1
    relay-log-purge = 1
    key_buffer_size = 15M
    read_buffer_size = 8M
    read_rnd_buffer_size = 16M
    bulk_insert_buffer_size = 64M
    myisam_sort_buffer_size = 128M
    myisam_repair_threads = 1
    lock_wait_timeout = 3600
    explicit_defaults_for_timestamp = 1
    innodb_thread_concurrency = 0
    innodb_sync_spin_loops = 100
    innodb_spin_wait_delay = 30
    
    transaction_isolation = REPEATABLE-READ
    innodb_buffer_pool_size = 4014M
    innodb_buffer_pool_instances = 4
    innodb_buffer_pool_load_at_startup = 1
    innodb_buffer_pool_dump_at_shutdown = 1
    innodb_data_file_path = ibdata1:1G:autoextend
    innodb_flush_log_at_trx_commit = 1
    innodb_log_buffer_size = 32M
    innodb_log_file_size = 2G
    innodb_log_files_in_group = 2
    
    innodb_io_capacity = 4000
    innodb_io_capacity_max = 8000
    innodb_flush_sync = 0
    innodb_flush_neighbors = 0
    innodb_write_io_threads = 8
    innodb_read_io_threads = 8
    innodb_purge_threads = 4
    innodb_page_cleaners = 4
    innodb_open_files = 65535
    innodb_max_dirty_pages_pct = 50
    innodb_flush_method = O_DIRECT
    innodb_lru_scan_depth = 4000
    innodb_checksum_algorithm = crc32
    innodb_lock_wait_timeout = 10
    innodb_rollback_on_timeout = 1
    innodb_print_all_deadlocks = 1
    innodb_file_per_table = 1
    innodb_stats_on_metadata = 0
    innodb_undo_log_truncate = 1
    
    
    [mysqldump]
    quick
    max_allowed_packet = 32M

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-server
  name: mysql-db-svc
  namespace: haagendazstest
spec:
  type: NodePort
  ports:
  - name: http
    port: 3306
    nodePort: 30337
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-server

---
# ------------------- App  ------------------- #
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-server
  namespace: haagendazstest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  serviceName: mysql-db-svc
  template:
    metadata:
      labels:
        app: mysql-server
    spec:

      nodeSelector:
        node: "haagendazstest"
      tolerations:
      - key: "node.kubernetes.io/unschedulable"
        operator: "Exists"
        effect: "NoSchedule"

      containers:
        - name: mysql-server
          image: 'mysql:5.7.28'
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_USER
              value: "user1"
            - name: MYSQL_PASSWORD
              value: "123456"
          # 存活检测
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1 
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          # 就绪检测
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1


          volumeMounts:
          - name: timezone
            mountPath: /etc/localtime
            readOnly: true
          - mountPath: /var/lib/mysql
            name: mysql-db-storage
          - name: config
            mountPath: /etc/my.cnf
            subPath: my.cnf
      volumes:
      - name: config
        configMap:
          name: mysql-db-config
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
  volumeClaimTemplates:
  - metadata:
      name: mysql-db-storage
    spec:
      accessModes:
      - ReadWriteMany
      storageClassName: "course-nfs-storage"
      resources:
        requests:
          storage: 50Gi
